/**
 * @file
 * @author jinguangguo
 * @date 2017/10/12
 */

export default {

    TRANSACTION_KEY: 'ASSETFEERATE', // 交易手续费
    ASSETFEERATE: 'ASSETFEERATE',
    PRICEPRECISION: 'PRICEPRECISION',
    AMOUNTPRECISION: 'AMOUNTPRECISION',
    HIGHLIGHTNO: 'HIGHLIGHTNO',

    SHOWSTATUS: 'SHOWSTATUS',

    WITHDRAW_TYPE_FEE: 'WITHDRAWMINFEE', // 提币手续费
    WITHDRAW_TYPE_MIN: 'WITHDRAWMIN',
    WITHDRAW_TYPE_MAX: 'WITHDRAWMAX',

    WITHDRAWMINFEE: 'WITHDRAWMINFEE',
    WITHDRAWMIN: 'WITHDRAWMIN',
    WITHDRAWMAX: 'WITHDRAWMAX',


    WITHDRAWLEVEL_0: 'WITHDRAWLEVEL_0',
    WITHDRAWLEVEL_1: 'WITHDRAWLEVEL_1',
    WITHDRAWLEVEL_2: 'WITHDRAWLEVEL_2',
    WITHDRAWLEVEL_3: 'WITHDRAWLEVEL_3',

    DEPOSITLEVEL_DEFAULT: 'DEPOSITLEVEL_DEFAULT', // 充值开关，0：开启，-1：关闭
    WITHDRAWPRECISION: 'WITHDRAWPRECISION', // 提现（钱包）精度
    ASSETCODECONFIRMNUM: 'ASSETCODECONFIRMNUM', // 网络确认数
    MODELKEY_1: 'AVAILABLE_MODEL_KEY', // 可用模型
    MODELKEY_2: 'LOCKING_AVAILABLE_MODEL_KEY', // 限制可用模型

    DEPOSIT_LOCK_PROPORTION: 'DEPOSIT_LOCK_PROPORTION', //充值锁仓
    MATCH_LOCKING_AVAILABL: 'MATCH_LOCKING_AVAILABL', //锁仓可用比列
    DAY_UNLOCKING_RATE: 'DAY_UNLOCKING_RATE', //每日释放比列
    MAX_DAY_UNLOCKING_RATE: 'MAX_DAY_UNLOCKING_RATE', //每日最高释放比列
    FIXED_PRICE_UP_RATE: 'FIXED_PRICE_UP_RATE', //价格上浮系数
    INVITE_UNLOCKING_REWARD_RATE: 'INVITE_UNLOCKING_REWARD_RATE', //直邀释放奖励比例
    TOP_INVITE_UNLOCKING_REWARD_RATE: 'TOP_INVITE_UNLOCKING_REWARD_RATE', //合伙人释放奖励比例
    DAY_LOCKING_SELL_NUMBER: 'DAY_LOCKING_SELL_NUMBER', //当天可一键卖出次数





    PRICE_COIN_LIST: [
        'UDC',
        'BTC',
        'ETH',
        'USDT',
        'DUSD',
        'KIPC'
        // 'ACT'
    ]

};